name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: OrlietPro
      fonts:
        - asset: assets/fonts/orliet_pro/OrlietProScript.otf
        - asset: assets/fonts/orliet_pro/OrlietProBold.otf
          weight: 700
        - asset: assets/fonts/orliet_pro/OrlietProItalic.otf
          style: italic  